# Trading System Configuration

# Data Management
data:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  cache_dir: "data/cache"
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - META
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 1d

# Backtesting Configuration
backtest:
  initial_capital: 100000.0
  commission: 0.001
  slippage: 0.0005
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  risk_per_trade: 0.02
  max_position_size: 0.1

# Strategy Parameters
strategy:
  moving_averages:
    short_window: 20
    long_window: 50
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9

# Machine Learning
ml:
  model_dir: models/
  train_test_split: 0.8
  validation_split: 0.1
  batch_size: 32
  epochs: 100
  early_stopping_patience: 10

# API Configuration
api:
  yfinance:
    timeout: 10
    retries: 3
    rate_limit: 2000  # requests per hour
  polygon:
    timeout: 10
    retries: 3
    rate_limit: 5000  # requests per minute
  alpha_vantage:
    api_key: "DUMMY_API_KEY"  # Set your API key here or use ALPHA_VANTAGE_API_KEY environment variable
    base_url: "https://www.alphavantage.co/query"
    rate_limit:
      calls_per_minute: 5
      calls_per_day: 500

# Logging
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level} | {message}"
  file: "logs/trading.log"
  max_size: 500MB
  backup_count: 10

# Database
database:
  host: localhost
  port: 27017
  name: trading
  collections:
    raw_data: raw_data
    processed_data: processed_data
    backtest_results: backtest_results
    model_metrics: model_metrics

# Visualization
visualization:
  style: seaborn
  context: paper
  palette: deep
  dpi: 300
  save_dir: plots/
